// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrmFtXnZFBxj9qRRQ10_ACQG7ZStd0YU',
    appId: '1:609068416384:web:e1662bbee2346e76c91565',
    messagingSenderId: '609068416384',
    projectId: 'official-mutual-transfer--gov',
    authDomain: 'official-mutual-transfer--gov.firebaseapp.com',
    storageBucket: 'official-mutual-transfer--gov.firebasestorage.app',
    measurementId: 'G-C1S6LBRNNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1L5XHXq5slD_HgBOnl8itW5DtpzA-Qbc',
    appId: '1:609068416384:android:e847da6c118db820c91565',
    messagingSenderId: '609068416384',
    projectId: 'official-mutual-transfer--gov',
    storageBucket: 'official-mutual-transfer--gov.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2JTzswH8sX-v4ZaxKhrjdf2Z0vMtDjOg',
    appId: '1:609068416384:ios:66853633e9bbf259c91565',
    messagingSenderId: '609068416384',
    projectId: 'official-mutual-transfer--gov',
    storageBucket: 'official-mutual-transfer--gov.firebasestorage.app',
    iosBundleId: 'lk.transfer.multiservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2JTzswH8sX-v4ZaxKhrjdf2Z0vMtDjOg',
    appId: '1:609068416384:ios:66853633e9bbf259c91565',
    messagingSenderId: '609068416384',
    projectId: 'official-mutual-transfer--gov',
    storageBucket: 'official-mutual-transfer--gov.firebasestorage.app',
    iosBundleId: 'lk.transfer.multiservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyrmFtXnZFBxj9qRRQ10_ACQG7ZStd0YU',
    appId: '1:609068416384:web:9606f0f2e74ae314c91565',
    messagingSenderId: '609068416384',
    projectId: 'official-mutual-transfer--gov',
    authDomain: 'official-mutual-transfer--gov.firebaseapp.com',
    storageBucket: 'official-mutual-transfer--gov.firebasestorage.app',
    measurementId: 'G-W0WHBWLELN',
  );
}
